### ISSUE TITLE
运行疑问

### ISSUE THREAD

**Issue by Tairraos** [Endier/ProxySwitchForMac#1]
你好。这个小app运行了没看到菜单栏图标呀？并且app本身也没有icon，显示的是一个默认的空白图标。
运行在 Sonoma 14.5 (23F79)

**Comment by Endier** [comment]
谢谢你的issue。
app图标是因为本来就没加，之前也尝试自己做了，但结果还没空白图标好看。
没有menubar图标的话就是bug了。因为本来觉得这个小app也没其他人用，就只在开发机和另外一台mac上简单测试了一下。既然现在他人有需要，那我会尽快修复的。

**Comment by Endier** [comment]
现在应该可以了，请你再试试。

**Comment by Endier** [comment]
现在应该可以了，请你再试试。

**Comment by Tairraos** [comment]
嗯，有图标了。不过sonoma 14.5需要在隐私里下降安全级别后才能正常使用。可以在readme里注明下
